package com.company;
import java.util.Scanner;
import java.util.Random;
public class rockpaperscissors {
    public static void main(String[] args) {
//        This is an Rock, Paper and Scissors game
//        Here,
//        Rock = 1
//        Paper = 2
//        Scissor = 3
        System.out.println("Entered the Item from menu:");
        System.out.println("ROCK = 1");
        System.out.println("PAPER = 2");
        System.out.println("SCISSORS = 3");
         Random num = new Random();
         int number = 0;
         for (int i=1 ; i<=1 ; i++ ){
             number = 1+num.nextInt(3);
         }
         //Now The user have to entered the num between and equal to 1 and 3
        Scanner sc = new Scanner(System.in);
         int num2 = sc.nextInt();
        System.out.println("The Num Entered By YOU is "+ num2);
        System.out.println("The Number Generated By AI is " + number);
         if (number==1 && num2==1 || number==2 && num2==2 || number==3 && num2==3){
             System.out.println("Play again");
         }else if (number==1 && num2==2){
             System.out.println("The user is winner");
         }else if (number==1 && num2==3){
             System.out.println("The AI is winner");
         }else if (number==2 && num2==1){
             System.out.println("The AI is winner");
         }else if (number==2 && num2==3){
             System.out.println("The user is winner");
         }else if (number==3 && num2==1){
             System.out.println("The user is winner");
         }else if (number==3 && num2==2){
             System.out.println("The user is winner");
         }
    }
}
